import { AppState, BrandId, Translations, BrandMarketData, PlatformData } from './types';

export const BRANDS: { id: BrandId; name: string; color: string; bg: string }[] = [
  { id: 'resound', name: 'ReSound', color: 'text-red-700', bg: 'bg-red-700' },
  { id: 'beltone', name: 'Beltone', color: 'text-blue-600', bg: 'bg-blue-600' },
  { id: 'other', name: 'Generic / Other', color: 'text-gray-800', bg: 'bg-gray-800' },
];

const INITIAL_PLATFORM_DATA = (): PlatformData => ({
  username: '',
  isActive: true,
  target: 'B2C',
  currentContentStyle: '',
  desiredContentStyle: '',
  organic: { 
    followers: 0, 
    avgMonthlyPosts: 0,
    reach: 0, 
    impressions: 0, 
    interactions: 0,
    engagementRate: 0, 
    profileVisits: 0,
    clicks: 0,
    posts: 0, 
    reels: 0, 
    videos: 0, 
    stories: 0, 
    videoViews: 0 
  },
  paid: { 
    advertisingEnabled: false,
    budget: 0, 
    avgMonthlyBudget: 0,
    cpc: 0, 
    ctr: 0, 
    conversions: 0, 
    cpl: 0 
  },
  checklist: {
    profilePic: false,
    clearBio: false,
    linkFunctional: false,
    visualCoherence: false
  },
  alignment: {
    colors: 'partial',
    typography: 'partial',
    tone: 'partial'
  }
});

const INITIAL_BRAND_MARKET_DATA = (): BrandMarketData => ({
  manager: '',
  hasCalendar: 'no',
  strategy: '',
  analysisPeriod: '90_days',
  metrics: {
    instagram: INITIAL_PLATFORM_DATA(),
    facebook: INITIAL_PLATFORM_DATA(),
    linkedin: INITIAL_PLATFORM_DATA(),
    youtube: INITIAL_PLATFORM_DATA(),
  },
});

export const INITIAL_STATE: AppState = {
  language: 'es',
  generalInfo: {
    projectName: '',
    date: new Date().toISOString().split('T')[0],
    objectives: '',
  },
  data: {
    es: { resound: INITIAL_BRAND_MARKET_DATA(), beltone: INITIAL_BRAND_MARKET_DATA() },
    br: { resound: INITIAL_BRAND_MARKET_DATA(), beltone: INITIAL_BRAND_MARKET_DATA() },
    it: { resound: INITIAL_BRAND_MARKET_DATA(), beltone: INITIAL_BRAND_MARKET_DATA() },
  },
  recommendations: [],
};

export const TRANSLATIONS: Translations = {
  es: {
    appTitle: 'Auditoría Global RRSS',
    dashboard: 'Dashboard',
    spain: 'España',
    brazil: 'Brasil',
    italy: 'Italia',
    recommendations: 'Recomendaciones',
    save: 'Guardar',
    export: 'Exportar JSON',
    import: 'Importar JSON',
    clear: 'Limpiar',
    language: 'Idioma',
    general: 'Información General',
    manager: 'Responsable',
    hasCalendar: '¿Calendario Editorial?',
    strategy: 'Notas Estrategia',
    analysisPeriod: 'Periodo Analizado',
    p_7: 'Últimos 7 días',
    p_28: 'Últimos 28 días',
    p_30: 'Últimos 30 días',
    p_90: 'Últimos 90 días',
    p_ytd: 'Año hasta la fecha (YTD)',
    organic: 'Métricas Orgánicas',
    paid: 'Publicidad (Ads)',
    healthAudit: 'Salud y Marca',
    username: 'Usuario',
    isActive: 'Activa',
    target: 'Público Target',
    currentContent: 'Contenido Actual',
    desiredContent: 'Contenido Deseado',
    avgMonthlyPosts: 'Posts/Mes (Avg)',
    avgMonthlyBudget: 'Inv. Mensual (Avg)',
    brandAlignment: 'Alineación Marca',
    lbl_colors: 'Colores',
    lbl_typo: 'Tipografía',
    lbl_tone: 'Tono',
    chk_profilePic: 'Foto Perfil OK',
    chk_bio: 'Bio Clara',
    chk_link: 'Link Funcional',
    chk_visual: 'Coh. Visual',
    followers: 'Seguidores',
    engagement: 'Eng. Rate (%)',
    interactions: 'Interacc. (Total)',
    impressions: 'Impresiones / Vistas',
    profileVisits: 'Visitas Perfil',
    clicks: 'Clics Enlace',
    lbl_posts: 'Post',
    lbl_reels: 'Reel',
    lbl_videos: 'Video',
    lbl_stories: 'Stry',
    reach: 'Alcance / Espectadores',
    videoViews: 'Vistas Video',
    budget: 'Inv. Periodo (€)',
    advertising: 'Publicidad Activa',
    cpc: 'CPC (€)',
    ctr: 'CTR (%)',
    conversions: 'Conversiones',
    cpl: 'CPL (€)',
    copyFromEs: 'Copiar de España',
    addRec: 'Añadir Recomendación',
    area: 'Área',
    problem: 'Problema',
    action: 'Acción',
    priority: 'Prioridad',
    high: 'Alta',
    medium: 'Media',
    low: 'Baja',
    totalBudget: 'Inv. Total',
    avgEngagement: 'Eng. Global',
    totalFollowers: 'Seguidores Tot.',
    brand: 'Marca',
    country: 'País/Mercado',
    global: 'Global / General',
    yes: 'Sí',
    no: 'No',
    partial: 'Parcial',
    copySummary: 'Copiar Resumen Ejecutivo',
    summaryCopied: '¡Resumen Copiado!',
    importSuccess: '¡Datos cargados correctamente!',
    importError: 'Error: Archivo inválido',
  },
  en: {
    appTitle: 'Global Social Audit',
    dashboard: 'Dashboard',
    spain: 'Spain',
    brazil: 'Brazil',
    italy: 'Italy',
    recommendations: 'Recommendations',
    save: 'Save',
    export: 'Export JSON',
    import: 'Import JSON',
    clear: 'Clear',
    language: 'Language',
    general: 'General Info',
    manager: 'Manager',
    hasCalendar: 'Editorial Calendar?',
    strategy: 'Strategy Notes',
    analysisPeriod: 'Analysis Period',
    p_7: 'Last 7 days',
    p_28: 'Last 28 days',
    p_30: 'Last 30 days',
    p_90: 'Last 90 days',
    p_ytd: 'Year to Date (YTD)',
    organic: 'Organic Metrics',
    paid: 'Paid (Ads)',
    healthAudit: 'Health & Brand',
    username: 'Username',
    isActive: 'Active',
    target: 'Target Audience',
    currentContent: 'Current Content',
    desiredContent: 'Desired Content',
    avgMonthlyPosts: 'Monthly Posts (Avg)',
    avgMonthlyBudget: 'Monthly Budget (Avg)',
    brandAlignment: 'Brand Alignment',
    lbl_colors: 'Colors',
    lbl_typo: 'Typography',
    lbl_tone: 'Tone',
    chk_profilePic: 'Profile Pic OK',
    chk_bio: 'Clear Bio',
    chk_link: 'Link Works',
    chk_visual: 'Visual Coh.',
    followers: 'Followers',
    engagement: 'Eng. Rate (%)',
    interactions: 'Interactions',
    impressions: 'Impressions / Views',
    profileVisits: 'Profile Visits',
    clicks: 'Link Clicks',
    lbl_posts: 'Post',
    lbl_reels: 'Reel',
    lbl_videos: 'Vid',
    lbl_stories: 'Stry',
    reach: 'Reach / Viewers',
    videoViews: 'Video Views',
    budget: 'Period Budget (€)',
    advertising: 'Ads Active',
    cpc: 'CPC (€)',
    ctr: 'CTR (%)',
    conversions: 'Conversions',
    cpl: 'CPL (€)',
    copyFromEs: 'Copy from Spain',
    addRec: 'Add Recommendation',
    area: 'Area',
    problem: 'Problem',
    action: 'Action',
    priority: 'Priority',
    high: 'High',
    medium: 'Medium',
    low: 'Low',
    totalBudget: 'Total Budget',
    avgEngagement: 'Global Eng.',
    totalFollowers: 'Total Followers',
    brand: 'Brand',
    country: 'Country/Market',
    global: 'Global / General',
    yes: 'Yes',
    no: 'No',
    partial: 'Partial',
    copySummary: 'Copy Executive Summary',
    summaryCopied: 'Summary Copied!',
    importSuccess: 'Data loaded successfully!',
    importError: 'Error: Invalid file',
  },
  it: {
    appTitle: 'Audit Social Globale',
    dashboard: 'Cruscotto',
    spain: 'Spagna',
    brazil: 'Brasile',
    italy: 'Italia',
    recommendations: 'Raccomandazioni',
    save: 'Salva',
    export: 'Esporta JSON',
    import: 'Importa JSON',
    clear: 'Pulisci',
    language: 'Lingua',
    general: 'Info Generali',
    manager: 'Responsabile',
    hasCalendar: 'Calendario Editoriale?',
    strategy: 'Note Strategiche',
    analysisPeriod: 'Periodo di Analisi',
    p_7: 'Ultimi 7 giorni',
    p_28: 'Ultimi 28 giorni',
    p_30: 'Ultimi 30 giorni',
    p_90: 'Ultimi 90 giorni',
    p_ytd: 'Da inizio anno',
    organic: 'Organico',
    paid: 'A Pagamento (Ads)',
    healthAudit: 'Salute & Brand',
    username: 'Username',
    isActive: 'Attiva',
    target: 'Target',
    currentContent: 'Contenuto Attuale',
    desiredContent: 'Contenuto Desiderato',
    avgMonthlyPosts: 'Post/Mese',
    avgMonthlyBudget: 'Budget/Mese',
    brandAlignment: 'Allineamento Brand',
    lbl_colors: 'Colori',
    lbl_typo: 'Font',
    lbl_tone: 'Tono',
    chk_profilePic: 'Foto Profilo OK',
    chk_bio: 'Bio Chiara',
    chk_link: 'Link Funz.',
    chk_visual: 'Coer. Visuale',
    followers: 'Follower',
    engagement: 'Eng. Rate (%)',
    interactions: 'Interazioni',
    impressions: 'Visualizzazioni',
    profileVisits: 'Visite Profilo',
    clicks: 'Click Link',
    lbl_posts: 'Post',
    lbl_reels: 'Reel',
    lbl_videos: 'Vid',
    lbl_stories: 'Stry',
    reach: 'Copertura / Spettatori',
    videoViews: 'Visualizzazioni',
    budget: 'Budget Periodo (€)',
    advertising: 'Ads Attive',
    cpc: 'CPC (€)',
    ctr: 'CTR (%)',
    conversions: 'Conversioni',
    cpl: 'CPL (€)',
    copyFromEs: 'Copia da Spagna',
    addRec: 'Aggiungi Raccomandazione',
    area: 'Area',
    problem: 'Problema',
    action: 'Azione',
    priority: 'Priorità',
    high: 'Alta',
    medium: 'Media',
    low: 'Bassa',
    totalBudget: 'Budget Tot.',
    avgEngagement: 'Eng. Globale',
    totalFollowers: 'Follower Tot.',
    brand: 'Marca',
    country: 'Paese',
    global: 'Globale / Generale',
    yes: 'Sì',
    no: 'No',
    partial: 'Parziale',
    copySummary: 'Copia Riepilogo Esecutivo',
    summaryCopied: 'Riepilogo Copiato!',
    importSuccess: 'Dati caricati con successo!',
    importError: 'Errore: File non valido',
  },
  pt: {
    appTitle: 'Auditoria Social Global',
    dashboard: 'Painel',
    spain: 'Espanha',
    brazil: 'Brasil',
    italy: 'Itália',
    recommendations: 'Recomendações',
    save: 'Salvar',
    export: 'Exportar JSON',
    import: 'Importar JSON',
    clear: 'Limpar',
    language: 'Idioma',
    general: 'Informações Gerais',
    manager: 'Responsável',
    hasCalendar: 'Calendário Editorial?',
    strategy: 'Notas Estratégia',
    analysisPeriod: 'Período de Análise',
    p_7: 'Últimos 7 dias',
    p_28: 'Últimos 28 dias',
    p_30: 'Últimos 30 dias',
    p_90: 'Últimos 90 dias',
    p_ytd: 'No ano (YTD)',
    organic: 'Métricas Orgânicas',
    paid: 'Pago (Ads)',
    healthAudit: 'Saúde & Marca',
    username: 'Usuário',
    isActive: 'Ativa',
    target: 'Público Target',
    currentContent: 'Conteúdo Atual',
    desiredContent: 'Conteúdo Desejado',
    avgMonthlyPosts: 'Posts/Mês',
    avgMonthlyBudget: 'Orç./Mês',
    brandAlignment: 'Alinhamento Marca',
    lbl_colors: 'Cores',
    lbl_typo: 'Tipo',
    lbl_tone: 'Tom',
    chk_profilePic: 'Foto Perfil OK',
    chk_bio: 'Bio Clara',
    chk_link: 'Link Func.',
    chk_visual: 'Coer. Visual',
    followers: 'Seguidores',
    engagement: 'Eng. Rate (%)',
    interactions: 'Interações',
    impressions: 'Visualizações',
    profileVisits: 'Visitas Perfil',
    clicks: 'Cliques Link',
    lbl_posts: 'Post',
    lbl_reels: 'Reel',
    lbl_videos: 'Vid',
    lbl_stories: 'Stry',
    reach: 'Alcance / Espectadores',
    videoViews: 'Visualizações',
    budget: 'Orç. Período (€)',
    advertising: 'Ads Ativo',
    cpc: 'CPC (€)',
    ctr: 'CTR (%)',
    conversions: 'Conversões',
    cpl: 'CPL (€)',
    copyFromEs: 'Copiar da Espanha',
    addRec: 'Adicionar Recomendación',
    area: 'Área',
    problem: 'Problema',
    action: 'Ação',
    priority: 'Prioridade',
    high: 'Alta',
    medium: 'Média',
    low: 'Baixa',
    totalBudget: 'Orç. Total',
    avgEngagement: 'Eng. Global',
    totalFollowers: 'Seguidores Tot.',
    brand: 'Marca',
    country: 'País',
    global: 'Global / Geral',
    yes: 'Sim',
    no: 'Não',
    partial: 'Parcial',
    copySummary: 'Copiar Resumo Executivo',
    summaryCopied: 'Resumo Copiado!',
    importSuccess: 'Dados carregados com sucesso!',
    importError: 'Erro: Arquivo inválido',
  },
};