import { AppState, BrandId, Translations, BrandMarketData, PlatformData } from './types';

export const BRANDS: { id: BrandId; name: string; color: string; bg: string }[] = [
  { id: 'resound', name: 'ReSound', color: 'text-red-700', bg: 'bg-red-700' },
  { id: 'beltone', name: 'Beltone', color: 'text-blue-600', bg: 'bg-blue-600' },
  { id: 'other', name: 'Generic / Other', color: 'text-gray-800', bg: 'bg-gray-800' },
];

const INITIAL_PLATFORM_DATA: PlatformData = {
  organic: { followers: 0, engagementRate: 0, posts: 0, reels: 0, videos: 0, stories: 0, reach: 0, videoViews: 0 },
  paid: { budget: 0, cpc: 0, ctr: 0, conversions: 0, cpl: 0 },
};

const INITIAL_BRAND_MARKET_DATA: BrandMarketData = {
  manager: '',
  hasCalendar: 'no',
  strategy: '',
  metrics: {
    instagram: JSON.parse(JSON.stringify(INITIAL_PLATFORM_DATA)),
    facebook: JSON.parse(JSON.stringify(INITIAL_PLATFORM_DATA)),
    linkedin: JSON.parse(JSON.stringify(INITIAL_PLATFORM_DATA)),
    youtube: JSON.parse(JSON.stringify(INITIAL_PLATFORM_DATA)),
  },
};

export const INITIAL_STATE: AppState = {
  language: 'es',
  generalInfo: {
    projectName: '',
    date: new Date().toISOString().split('T')[0],
    objectives: '',
  },
  data: {
    // All countries now have ReSound AND Beltone
    es: {
      resound: JSON.parse(JSON.stringify(INITIAL_BRAND_MARKET_DATA)),
      beltone: JSON.parse(JSON.stringify(INITIAL_BRAND_MARKET_DATA)),
    },
    br: {
      resound: JSON.parse(JSON.stringify(INITIAL_BRAND_MARKET_DATA)),
      beltone: JSON.parse(JSON.stringify(INITIAL_BRAND_MARKET_DATA)),
    },
    it: {
      resound: JSON.parse(JSON.stringify(INITIAL_BRAND_MARKET_DATA)),
      beltone: JSON.parse(JSON.stringify(INITIAL_BRAND_MARKET_DATA)),
    },
  },
  recommendations: [],
};

export const TRANSLATIONS: Translations = {
  es: {
    appTitle: 'Auditoría Global RRSS',
    dashboard: 'Dashboard',
    spain: 'España',
    brazil: 'Brasil',
    italy: 'Italia',
    recommendations: 'Recomendaciones',
    save: 'Guardar',
    export: 'Exportar JSON',
    import: 'Importar JSON',
    clear: 'Limpiar',
    language: 'Idioma',
    general: 'Información General',
    manager: 'Responsable',
    hasCalendar: '¿Calendario Editorial?',
    strategy: 'Notas Estrategia',
    organic: 'Orgánico',
    paid: 'Pagado (Ads)',
    metrics: 'Métricas',
    instagram: 'Instagram',
    facebook: 'Facebook',
    linkedin: 'LinkedIn',
    youtube: 'YouTube',
    followers: 'Seguidores',
    engagement: 'Eng. Rate (%)',
    frequency: 'Frec/Semana',
    contentMix: 'Mix Contenido',
    lbl_posts: 'Post',
    lbl_reels: 'Reel',
    lbl_videos: 'Video',
    lbl_stories: 'Stry',
    reach: 'Alcance',
    videoViews: 'Vistas Video',
    budget: 'Inversión (€)',
    cpc: 'CPC (€)',
    ctr: 'CTR (%)',
    conversions: 'Conversiones',
    cpl: 'CPL (€)',
    copyFromEs: 'Copiar de España (ReSound + Beltone)',
    addRec: 'Añadir Recomendación',
    area: 'Área',
    problem: 'Problema',
    action: 'Acción',
    priority: 'Prioridad',
    high: 'Alta',
    medium: 'Media',
    low: 'Baja',
    totalBudget: 'Inv. Total',
    avgEngagement: 'Eng. Global',
    totalFollowers: 'Seguidores Tot.',
    brand: 'Marca',
    country: 'País/Mercado',
    global: 'Global / General',
    yes: 'Sí',
    no: 'No',
    partial: 'Parcial',
    copySummary: 'Copiar Resumen Ejecutivo',
    summaryCopied: '¡Resumen Copiado!',
    importSuccess: '¡Datos cargados correctamente!',
    importError: 'Error: Archivo inválido',
  },
  en: {
    appTitle: 'Global Social Audit',
    dashboard: 'Dashboard',
    spain: 'Spain',
    brazil: 'Brazil',
    italy: 'Italy',
    recommendations: 'Recommendations',
    save: 'Save',
    export: 'Export JSON',
    import: 'Import JSON',
    clear: 'Clear',
    language: 'Language',
    general: 'General Info',
    manager: 'Manager',
    hasCalendar: 'Editorial Calendar?',
    strategy: 'Strategy Notes',
    organic: 'Organic',
    paid: 'Paid (Ads)',
    metrics: 'Metrics',
    instagram: 'Instagram',
    facebook: 'Facebook',
    linkedin: 'LinkedIn',
    youtube: 'YouTube',
    followers: 'Followers',
    engagement: 'Eng. Rate (%)',
    frequency: 'Freq/Week',
    contentMix: 'Content Mix',
    lbl_posts: 'Post',
    lbl_reels: 'Reel',
    lbl_videos: 'Vid',
    lbl_stories: 'Stry',
    reach: 'Reach',
    videoViews: 'Video Views',
    budget: 'Budget (€)',
    cpc: 'CPC (€)',
    ctr: 'CTR (%)',
    conversions: 'Conversions',
    cpl: 'CPL (€)',
    copyFromEs: 'Copy from Spain (ReSound + Beltone)',
    addRec: 'Add Recommendation',
    area: 'Area',
    problem: 'Problem',
    action: 'Action',
    priority: 'Priority',
    high: 'High',
    medium: 'Medium',
    low: 'Low',
    totalBudget: 'Total Budget',
    avgEngagement: 'Global Eng.',
    totalFollowers: 'Total Followers',
    brand: 'Brand',
    country: 'Country/Market',
    global: 'Global / General',
    yes: 'Yes',
    no: 'No',
    partial: 'Partial',
    copySummary: 'Copy Executive Summary',
    summaryCopied: 'Summary Copied!',
    importSuccess: 'Data loaded successfully!',
    importError: 'Error: Invalid file',
  },
  it: {
    appTitle: 'Audit Social Globale',
    dashboard: 'Cruscotto',
    spain: 'Spagna',
    brazil: 'Brasile',
    italy: 'Italia',
    recommendations: 'Raccomandazioni',
    save: 'Salva',
    export: 'Esporta JSON',
    import: 'Importa JSON',
    clear: 'Pulisci',
    language: 'Lingua',
    general: 'Info Generali',
    manager: 'Responsabile',
    hasCalendar: 'Calendario Editoriale?',
    strategy: 'Note Strategiche',
    organic: 'Organico',
    paid: 'A Pagamento (Ads)',
    metrics: 'Metriche',
    instagram: 'Instagram',
    facebook: 'Facebook',
    linkedin: 'LinkedIn',
    youtube: 'YouTube',
    followers: 'Follower',
    engagement: 'Eng. Rate (%)',
    frequency: 'Freq/Sett',
    contentMix: 'Mix Contenuti',
    lbl_posts: 'Post',
    lbl_reels: 'Reel',
    lbl_videos: 'Vid',
    lbl_stories: 'Stry',
    reach: 'Copertura',
    videoViews: 'Visualizzazioni',
    budget: 'Budget (€)',
    cpc: 'CPC (€)',
    ctr: 'CTR (%)',
    conversions: 'Conversioni',
    cpl: 'CPL (€)',
    copyFromEs: 'Copia da Spagna (ReSound + Beltone)',
    addRec: 'Aggiungi Raccomandazione',
    area: 'Area',
    problem: 'Problema',
    action: 'Azione',
    priority: 'Priorità',
    high: 'Alta',
    medium: 'Media',
    low: 'Bassa',
    totalBudget: 'Budget Tot.',
    avgEngagement: 'Eng. Globale',
    totalFollowers: 'Follower Tot.',
    brand: 'Marca',
    country: 'Paese',
    global: 'Globale / Generale',
    yes: 'Sì',
    no: 'No',
    partial: 'Parziale',
    copySummary: 'Copia Riepilogo Esecutivo',
    summaryCopied: 'Riepilogo Copiato!',
    importSuccess: 'Dati caricati con successo!',
    importError: 'Errore: File non valido',
  },
  pt: {
    appTitle: 'Auditoria Social Global',
    dashboard: 'Painel',
    spain: 'Espanha',
    brazil: 'Brasil',
    italy: 'Itália',
    recommendations: 'Recomendações',
    save: 'Salvar',
    export: 'Exportar JSON',
    import: 'Importar JSON',
    clear: 'Limpar',
    language: 'Idioma',
    general: 'Informações Gerais',
    manager: 'Responsável',
    hasCalendar: 'Calendário Editorial?',
    strategy: 'Notas Estratégia',
    organic: 'Orgânico',
    paid: 'Pago (Ads)',
    metrics: 'Métricas',
    instagram: 'Instagram',
    facebook: 'Facebook',
    linkedin: 'LinkedIn',
    youtube: 'YouTube',
    followers: 'Seguidores',
    engagement: 'Eng. Rate (%)',
    frequency: 'Freq/Semana',
    contentMix: 'Mix Conteúdo',
    lbl_posts: 'Post',
    lbl_reels: 'Reel',
    lbl_videos: 'Vid',
    lbl_stories: 'Stry',
    reach: 'Alcance',
    videoViews: 'Visualizações',
    budget: 'Orçamento (€)',
    cpc: 'CPC (€)',
    ctr: 'CTR (%)',
    conversions: 'Conversões',
    cpl: 'CPL (€)',
    copyFromEs: 'Copiar da Espanha (ReSound + Beltone)',
    addRec: 'Adicionar Recomendação',
    area: 'Área',
    problem: 'Problema',
    action: 'Ação',
    priority: 'Prioridade',
    high: 'Alta',
    medium: 'Média',
    low: 'Baixa',
    totalBudget: 'Orç. Total',
    avgEngagement: 'Eng. Global',
    totalFollowers: 'Seguidores Tot.',
    brand: 'Marca',
    country: 'País',
    global: 'Global / Geral',
    yes: 'Sim',
    no: 'Não',
    partial: 'Parcial',
    copySummary: 'Copiar Resumo Executivo',
    summaryCopied: 'Resumo Copiado!',
    importSuccess: 'Dados carregados com sucesso!',
    importError: 'Erro: Arquivo inválido',
  },
};